### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-sdk-js#148]
```
TypeError: Cannot read property 'startsWith' of undefined
    at Function.convertSignatureStringToRsv (/home/gnu/my-project/node_modules/codechain-sdk/lib/core/SignedParcel.js:145:23)
    at new SignedParcel (/home/gnu/my-project/node_modules/codechain-sdk/lib/core/SignedParcel.js:35:42)
    at ChainRpc.<anonymous> (/home/gnu/my-project/node_modules/codechain-sdk/lib/rpc/chain.js:68:42)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gnu/my-project/node_modules/codechain-sdk/lib/rpc/chain.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

To print a proper error message, The `sig` field must be validated in `SignedParcel` constructor.

**Comment by joojis** [comment]
The error occurs when the signature is undefined.
The signature was able to be undefined when the sign() RPC call returned undefined. It was fixed after the patch validating RPC responses. https://github.com/CodeChain-io/codechain-sdk-js/commit/232df26dd40ec0e273d16a068473243b5ede9810
