### ISSUE TITLE
Integration test fails

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-sdk-js#87]
```
 FAIL  integration_tests/examples.spec.ts
  ● payment

    Cannot find module 'codechain-sdk' from 'payment.js'

    > 1 | var SDK = require("codechain-sdk");
      2 | 
      3 | var sdk = new SDK({ server: "http://localhost:8080" });
      4 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (examples/payment.js:1:38)

  ● mint-and-transfer

    Cannot find module 'codechain-sdk' from 'mint-and-transfer.js'

    > 1 | const SDK = require("codechain-sdk");
      2 | 
      3 | const sdk = new SDK({ server: "http://localhost:8080" });
      4 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (examples/mint-and-transfer.js:1:40)
```

**Comment by joojis** [comment]
Fixed at https://github.com/CodeChain-io/codechain-sdk-js/commit/5ff9393daadc93ff2986ccac0848d7d79313d3a0
